name: rabbitmq test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      rabbit:
        image: rabbitmq:latest
        ports:
          - 5672:5672
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2

      - name: Install poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install dependencies
        run: poetry install

      - name: Execute script
        run: poetry run python rabbitmq_connection.py
        env:
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          AMQP_URL: amqp://guest:guest@$RABBITMQ_HOST:$RABBITMQ_PORT
